FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# DistributionAPI

Distribution API is an API to submit loan application.

# Data Structures

## CustomerIdentity (object)
+ first_name: xxx (string, required)
+ last_name: xxx (string, required)
+ birth_name: xxxx (string, optional) - maiden name
+ birth_date: 19722703 (string,required) - yyyymmdd

## Monetary (object)
+ amount: 123.12 (number,required)
+ devise: USD (string,required)

## Customer (object)
+ identity (CustomerIdentity,required)


## Project (object)
+ amount (Monetary, required) - The total amount of the basket
+ duration: 6 (number, optional) - The loan duration in month
+ term (Monetary, optional) - The monthly payment
+ kind : HIGH_TEC (string,required) - The basket kind

## Init tx request (object)
+ vendorId: 100 (string,required) - The vendor id of the pos
+ customer  (Customer,required) - The customer identity at least
+ project (Project,required) - The customer project


## Initialise transaction [/transaction]

### Initialise a transaction [POST]

Initialise a transaction allows you to start a new loan transaction.
If the customer identity is sent, it will be used to give the best matching proposal.

+ Request (application/json)

 + Attributes (Init tx request)

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]