FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# DistributionAPI

Distribution API is an API to submit loan application.

## Initialise transaction [/transaction]

### Initialise a transaction [POST]

Initialise a transaction allows you to start a new loan transaction.
If the customer identity is sent, it will be used to give the best matching proposal.

+ Request (application/json)

        {
            "vendor_id": "The PF vendor identifier",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }


+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]